package com.pokebuddy.iv

/**
 * Move data from the bundled `moves.csv` asset (generated by `scripts/make_base_stats.py`).
 *
 * IMPORTANT: these are pvpoke's **PvP** numbers. Pokémon GO uses different power and timing
 * values for PvE (raids and gyms), so anything ranked from them is an approximation outside
 * PvP — callers must present it as such rather than as a definitive "best counter".
 */
object MoveTable {

    data class Move(
        val id: String,
        val name: String,
        val type: String,
        val power: Int,
        /** Cost to fire a charged move. 0 for fast moves. */
        val energy: Int,
        /** Energy generated by a fast move. 0 for charged moves. */
        val energyGain: Int,
        val cooldown: Int,
        val turns: Int,
    ) {
        val isFast: Boolean get() = energyGain > 0

        /**
         * Damage per turn, ignoring the defender. Fast moves run on their own cadence;
         * charged moves are amortised over the fast-move turns needed to charge them,
         * which is why a big nuke doesn't automatically outrank a cheap spam move.
         */
        fun damagePerTurn(): Double = when {
            isFast -> power.toDouble() / turns.coerceAtLeast(1)
            energy > 0 -> power.toDouble() / energy   // damage per unit energy
            else -> power.toDouble()
        }
    }

    @Volatile private var byId: Map<String, Move> = emptyMap()

    fun load(csv: String) {
        byId = parse(csv)
    }

    fun parse(csv: String): Map<String, Move> {
        val map = HashMap<String, Move>()
        for (line in csv.lineSequence()) {
            if (line.isBlank() || line.startsWith("id,")) continue
            val p = line.split(',')
            if (p.size < 8) continue
            val id = p[0].trim()
            map[id] = Move(
                id = id,
                name = p[1].trim(),
                type = p[2].trim().lowercase(),
                power = p[3].trim().toIntOrNull() ?: 0,
                energy = p[4].trim().toIntOrNull() ?: 0,
                energyGain = p[5].trim().toIntOrNull() ?: 0,
                cooldown = p[6].trim().toIntOrNull() ?: 0,
                turns = p[7].trim().toIntOrNull() ?: 0,
            )
        }
        return map
    }

    val size: Int get() = byId.size

    operator fun get(id: String): Move? = byId[id.trim().uppercase().replace(' ', '_')]

    /** Lookup by the human name shown on the detail screen ("Quick Attack"). */
    fun byName(name: String): Move? {
        val n = name.trim().lowercase()
        return byId.values.firstOrNull { it.name.lowercase() == n }
    }
}
