package com.pokebuddy.iv

/**
 * Species table for the full Pokédex, loaded from the bundled `base_stats.csv` asset
 * (generated by `scripts/make_base_stats.py` from public GameMaster data). No network: the
 * CSV ships inside the APK.
 *
 * Columns: `key,dex,name,atk,def,hp,types,family`. The older 4-column
 * `key,atk,def,hp` form is still accepted so small inline fixtures stay readable in tests.
 *
 * Forms are keyed by their full display name ("Raichu (Alolan)" → `raichualolan`). Because
 * the game does not always spell the form out on the detail screen, prefer [resolve], which
 * uses the on-screen TYPES to tell forms apart — see the note there.
 */
object SpeciesTable {

    data class Species(
        val key: String,
        val dex: Int,
        val name: String,
        val stats: BaseStats,
        val types: List<String>,
        val family: String,
    ) {
        /**
         * Mega/Primal forms are a temporary battle state, not something you own: mega
         * evolving doesn't create a new Pokémon or change its IVs. They're excluded from
         * form disambiguation so they can't compete with the real forms — plain Raichu,
         * Mega Raichu X and Mega Raichu Y are all pure electric, which would otherwise
         * make every ordinary Raichu ambiguous.
         */
        val isTransientForm: Boolean
            get() = name.contains("(Mega") || name.contains("(Primal")
    }

    @Volatile private var byKey: Map<String, Species> = emptyMap()
    /** Display name with any "(Form)" suffix stripped → every species sharing it. */
    @Volatile private var byBaseName: Map<String, List<Species>> = emptyMap()

    fun load(csv: String) {
        val parsed = parse(csv)
        byKey = parsed
        byBaseName = parsed.values
            .filterNot { it.isTransientForm }
            .groupBy { baseName(it.name) }
    }

    fun parse(csv: String): Map<String, Species> {
        val map = HashMap<String, Species>()
        for (line in csv.lineSequence()) {
            if (line.isBlank() || line.startsWith("key,")) continue   // header
            val p = line.split(',')
            val species = when {
                p.size >= 8 -> {
                    val atk = p[3].trim().toIntOrNull() ?: continue
                    val def = p[4].trim().toIntOrNull() ?: continue
                    val hp = p[5].trim().toIntOrNull() ?: continue
                    Species(
                        key = p[0].trim(),
                        dex = p[1].trim().toIntOrNull() ?: 0,
                        name = p[2].trim(),
                        stats = BaseStats(atk, def, hp),
                        types = p[6].split('|').map { it.trim() }.filter { it.isNotEmpty() },
                        family = p[7].trim(),
                    )
                }
                // Legacy/inline fixture rows: key,atk,def,hp
                p.size >= 4 -> {
                    val atk = p[1].trim().toIntOrNull() ?: continue
                    val def = p[2].trim().toIntOrNull() ?: continue
                    val hp = p[3].trim().toIntOrNull() ?: continue
                    val key = p[0].trim()
                    Species(key, 0, key, BaseStats(atk, def, hp), emptyList(), "")
                }
                else -> continue
            }
            map[species.key] = species
        }
        return map
    }

    fun normalize(name: String): String =
        name.lowercase().filter { it.isLetterOrDigit() }

    /** "Raichu (Alolan)" → "raichu"; plain names normalize unchanged. */
    private fun baseName(displayName: String): String =
        normalize(displayName.substringBefore('('))

    val size: Int get() = byKey.size

    /** Form words the game may show BEFORE the species name ("Alolan Raichu"). */
    private val FORM_PREFIXES = listOf(
        "alolan", "galarian", "hisuian", "paldean", "mega", "primal", "origin",
    )

    fun species(name: String): Species? {
        val key = normalize(name)
        byKey[key]?.let { return it }
        // The game may lead with the form word while the key trails it.
        for (form in FORM_PREFIXES) {
            if (!key.startsWith(form) || key.length <= form.length) continue
            val rest = key.removePrefix(form)
            byKey[rest + form]?.let { return it }
            val last = rest.last()
            if (rest.length > 1 && (last == 'x' || last == 'y')) {
                byKey[rest.dropLast(1) + form + last]?.let { return it }
            }
        }
        return null
    }

    /**
     * Resolves a name PLUS the types read off the same screen.
     *
     * This exists because the detail screen may show a bare "Raichu" for an Alolan Raichu,
     * with only an icon marking the form. Scoring it against plain Raichu's stats would
     * yield a confidently wrong IV — so when a name maps to several forms we disambiguate
     * on type (Alolan Raichu is electric/psychic; plain Raichu is electric).
     *
     * Returns null when the forms genuinely cannot be told apart (Deoxys' forms are all
     * pure psychic), because a coin flip between them is exactly the guess-as-certainty
     * this project refuses to make.
     */
    fun resolve(name: String, types: List<String>): Species? {
        val candidates = byBaseName[normalize(name)].orEmpty()
        // Nothing to disambiguate: either the name is already form-specific ("Alolan
        // Marowak"), or the species simply has no alternate forms. NB a bare base name
        // still matches its own key here, so this check must come BEFORE any direct
        // key lookup — otherwise "Raichu" resolves to plain Raichu and the types below
        // never get a say.
        if (candidates.size <= 1) return species(name)

        if (types.isNotEmpty()) {
            val wanted = types.map { it.lowercase() }.toSet()
            val byType = candidates.filter { it.types.toSet() == wanted }
            if (byType.size == 1) return byType.single()
        }
        return null
    }

    operator fun get(name: String): BaseStats? = species(name)?.stats
}
